// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

public interface AggregateDetectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yolo.AggregateDetectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  java.util.List<com.yolo.proto.Detection> 
      getDetectionsList();
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  com.yolo.proto.Detection getDetections(int index);
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  int getDetectionsCount();
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  java.util.List<? extends com.yolo.proto.DetectionOrBuilder> 
      getDetectionsOrBuilderList();
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  com.yolo.proto.DetectionOrBuilder getDetectionsOrBuilder(
      int index);

  /**
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  int getTotalCount();

  /**
   * <pre>
   * JPEG 标注图
   * </pre>
   *
   * <code>bytes annotated_image = 3;</code>
   * @return The annotatedImage.
   */
  com.google.protobuf.ByteString getAnnotatedImage();

  /**
   * <code>int32 processing_time_ms = 4;</code>
   * @return The processingTimeMs.
   */
  int getProcessingTimeMs();
}
