// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

/**
 * <pre>
 * ============================================================
 * 网关聚合响应（包含标注图）
 * ============================================================
 * </pre>
 *
 * Protobuf type {@code yolo.AggregateDetectResponse}
 */
public final class AggregateDetectResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yolo.AggregateDetectResponse)
    AggregateDetectResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AggregateDetectResponse.newBuilder() to construct.
  private AggregateDetectResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AggregateDetectResponse() {
    detections_ = java.util.Collections.emptyList();
    annotatedImage_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AggregateDetectResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_AggregateDetectResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_AggregateDetectResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yolo.proto.AggregateDetectResponse.class, com.yolo.proto.AggregateDetectResponse.Builder.class);
  }

  public static final int DETECTIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.yolo.proto.Detection> detections_;
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.yolo.proto.Detection> getDetectionsList() {
    return detections_;
  }
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yolo.proto.DetectionOrBuilder> 
      getDetectionsOrBuilderList() {
    return detections_;
  }
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  @java.lang.Override
  public int getDetectionsCount() {
    return detections_.size();
  }
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  @java.lang.Override
  public com.yolo.proto.Detection getDetections(int index) {
    return detections_.get(index);
  }
  /**
   * <code>repeated .yolo.Detection detections = 1;</code>
   */
  @java.lang.Override
  public com.yolo.proto.DetectionOrBuilder getDetectionsOrBuilder(
      int index) {
    return detections_.get(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 2;
  private int totalCount_ = 0;
  /**
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }

  public static final int ANNOTATED_IMAGE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString annotatedImage_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * JPEG 标注图
   * </pre>
   *
   * <code>bytes annotated_image = 3;</code>
   * @return The annotatedImage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAnnotatedImage() {
    return annotatedImage_;
  }

  public static final int PROCESSING_TIME_MS_FIELD_NUMBER = 4;
  private int processingTimeMs_ = 0;
  /**
   * <code>int32 processing_time_ms = 4;</code>
   * @return The processingTimeMs.
   */
  @java.lang.Override
  public int getProcessingTimeMs() {
    return processingTimeMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < detections_.size(); i++) {
      output.writeMessage(1, detections_.get(i));
    }
    if (totalCount_ != 0) {
      output.writeInt32(2, totalCount_);
    }
    if (!annotatedImage_.isEmpty()) {
      output.writeBytes(3, annotatedImage_);
    }
    if (processingTimeMs_ != 0) {
      output.writeInt32(4, processingTimeMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < detections_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, detections_.get(i));
    }
    if (totalCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalCount_);
    }
    if (!annotatedImage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, annotatedImage_);
    }
    if (processingTimeMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, processingTimeMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yolo.proto.AggregateDetectResponse)) {
      return super.equals(obj);
    }
    com.yolo.proto.AggregateDetectResponse other = (com.yolo.proto.AggregateDetectResponse) obj;

    if (!getDetectionsList()
        .equals(other.getDetectionsList())) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getAnnotatedImage()
        .equals(other.getAnnotatedImage())) return false;
    if (getProcessingTimeMs()
        != other.getProcessingTimeMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDetectionsCount() > 0) {
      hash = (37 * hash) + DETECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getDetectionsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalCount();
    hash = (37 * hash) + ANNOTATED_IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getAnnotatedImage().hashCode();
    hash = (37 * hash) + PROCESSING_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + getProcessingTimeMs();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yolo.proto.AggregateDetectResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yolo.proto.AggregateDetectResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.AggregateDetectResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yolo.proto.AggregateDetectResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ============================================================
   * 网关聚合响应（包含标注图）
   * ============================================================
   * </pre>
   *
   * Protobuf type {@code yolo.AggregateDetectResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yolo.AggregateDetectResponse)
      com.yolo.proto.AggregateDetectResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_AggregateDetectResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_AggregateDetectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yolo.proto.AggregateDetectResponse.class, com.yolo.proto.AggregateDetectResponse.Builder.class);
    }

    // Construct using com.yolo.proto.AggregateDetectResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (detectionsBuilder_ == null) {
        detections_ = java.util.Collections.emptyList();
      } else {
        detections_ = null;
        detectionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalCount_ = 0;
      annotatedImage_ = com.google.protobuf.ByteString.EMPTY;
      processingTimeMs_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_AggregateDetectResponse_descriptor;
    }

    @java.lang.Override
    public com.yolo.proto.AggregateDetectResponse getDefaultInstanceForType() {
      return com.yolo.proto.AggregateDetectResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.yolo.proto.AggregateDetectResponse build() {
      com.yolo.proto.AggregateDetectResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yolo.proto.AggregateDetectResponse buildPartial() {
      com.yolo.proto.AggregateDetectResponse result = new com.yolo.proto.AggregateDetectResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yolo.proto.AggregateDetectResponse result) {
      if (detectionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          detections_ = java.util.Collections.unmodifiableList(detections_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.detections_ = detections_;
      } else {
        result.detections_ = detectionsBuilder_.build();
      }
    }

    private void buildPartial0(com.yolo.proto.AggregateDetectResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalCount_ = totalCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.annotatedImage_ = annotatedImage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.processingTimeMs_ = processingTimeMs_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yolo.proto.AggregateDetectResponse) {
        return mergeFrom((com.yolo.proto.AggregateDetectResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yolo.proto.AggregateDetectResponse other) {
      if (other == com.yolo.proto.AggregateDetectResponse.getDefaultInstance()) return this;
      if (detectionsBuilder_ == null) {
        if (!other.detections_.isEmpty()) {
          if (detections_.isEmpty()) {
            detections_ = other.detections_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDetectionsIsMutable();
            detections_.addAll(other.detections_);
          }
          onChanged();
        }
      } else {
        if (!other.detections_.isEmpty()) {
          if (detectionsBuilder_.isEmpty()) {
            detectionsBuilder_.dispose();
            detectionsBuilder_ = null;
            detections_ = other.detections_;
            bitField0_ = (bitField0_ & ~0x00000001);
            detectionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDetectionsFieldBuilder() : null;
          } else {
            detectionsBuilder_.addAllMessages(other.detections_);
          }
        }
      }
      if (other.getTotalCount() != 0) {
        setTotalCount(other.getTotalCount());
      }
      if (other.getAnnotatedImage() != com.google.protobuf.ByteString.EMPTY) {
        setAnnotatedImage(other.getAnnotatedImage());
      }
      if (other.getProcessingTimeMs() != 0) {
        setProcessingTimeMs(other.getProcessingTimeMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.yolo.proto.Detection m =
                  input.readMessage(
                      com.yolo.proto.Detection.parser(),
                      extensionRegistry);
              if (detectionsBuilder_ == null) {
                ensureDetectionsIsMutable();
                detections_.add(m);
              } else {
                detectionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              totalCount_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              annotatedImage_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              processingTimeMs_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.yolo.proto.Detection> detections_ =
      java.util.Collections.emptyList();
    private void ensureDetectionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        detections_ = new java.util.ArrayList<com.yolo.proto.Detection>(detections_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yolo.proto.Detection, com.yolo.proto.Detection.Builder, com.yolo.proto.DetectionOrBuilder> detectionsBuilder_;

    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public java.util.List<com.yolo.proto.Detection> getDetectionsList() {
      if (detectionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(detections_);
      } else {
        return detectionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public int getDetectionsCount() {
      if (detectionsBuilder_ == null) {
        return detections_.size();
      } else {
        return detectionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public com.yolo.proto.Detection getDetections(int index) {
      if (detectionsBuilder_ == null) {
        return detections_.get(index);
      } else {
        return detectionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder setDetections(
        int index, com.yolo.proto.Detection value) {
      if (detectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetectionsIsMutable();
        detections_.set(index, value);
        onChanged();
      } else {
        detectionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder setDetections(
        int index, com.yolo.proto.Detection.Builder builderForValue) {
      if (detectionsBuilder_ == null) {
        ensureDetectionsIsMutable();
        detections_.set(index, builderForValue.build());
        onChanged();
      } else {
        detectionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder addDetections(com.yolo.proto.Detection value) {
      if (detectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetectionsIsMutable();
        detections_.add(value);
        onChanged();
      } else {
        detectionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder addDetections(
        int index, com.yolo.proto.Detection value) {
      if (detectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetectionsIsMutable();
        detections_.add(index, value);
        onChanged();
      } else {
        detectionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder addDetections(
        com.yolo.proto.Detection.Builder builderForValue) {
      if (detectionsBuilder_ == null) {
        ensureDetectionsIsMutable();
        detections_.add(builderForValue.build());
        onChanged();
      } else {
        detectionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder addDetections(
        int index, com.yolo.proto.Detection.Builder builderForValue) {
      if (detectionsBuilder_ == null) {
        ensureDetectionsIsMutable();
        detections_.add(index, builderForValue.build());
        onChanged();
      } else {
        detectionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder addAllDetections(
        java.lang.Iterable<? extends com.yolo.proto.Detection> values) {
      if (detectionsBuilder_ == null) {
        ensureDetectionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, detections_);
        onChanged();
      } else {
        detectionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder clearDetections() {
      if (detectionsBuilder_ == null) {
        detections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        detectionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public Builder removeDetections(int index) {
      if (detectionsBuilder_ == null) {
        ensureDetectionsIsMutable();
        detections_.remove(index);
        onChanged();
      } else {
        detectionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public com.yolo.proto.Detection.Builder getDetectionsBuilder(
        int index) {
      return getDetectionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public com.yolo.proto.DetectionOrBuilder getDetectionsOrBuilder(
        int index) {
      if (detectionsBuilder_ == null) {
        return detections_.get(index);  } else {
        return detectionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public java.util.List<? extends com.yolo.proto.DetectionOrBuilder> 
         getDetectionsOrBuilderList() {
      if (detectionsBuilder_ != null) {
        return detectionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(detections_);
      }
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public com.yolo.proto.Detection.Builder addDetectionsBuilder() {
      return getDetectionsFieldBuilder().addBuilder(
          com.yolo.proto.Detection.getDefaultInstance());
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public com.yolo.proto.Detection.Builder addDetectionsBuilder(
        int index) {
      return getDetectionsFieldBuilder().addBuilder(
          index, com.yolo.proto.Detection.getDefaultInstance());
    }
    /**
     * <code>repeated .yolo.Detection detections = 1;</code>
     */
    public java.util.List<com.yolo.proto.Detection.Builder> 
         getDetectionsBuilderList() {
      return getDetectionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.yolo.proto.Detection, com.yolo.proto.Detection.Builder, com.yolo.proto.DetectionOrBuilder> 
        getDetectionsFieldBuilder() {
      if (detectionsBuilder_ == null) {
        detectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.yolo.proto.Detection, com.yolo.proto.Detection.Builder, com.yolo.proto.DetectionOrBuilder>(
                detections_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        detections_ = null;
      }
      return detectionsBuilder_;
    }

    private int totalCount_ ;
    /**
     * <code>int32 total_count = 2;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int32 total_count = 2;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {

      totalCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalCount_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString annotatedImage_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * JPEG 标注图
     * </pre>
     *
     * <code>bytes annotated_image = 3;</code>
     * @return The annotatedImage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAnnotatedImage() {
      return annotatedImage_;
    }
    /**
     * <pre>
     * JPEG 标注图
     * </pre>
     *
     * <code>bytes annotated_image = 3;</code>
     * @param value The annotatedImage to set.
     * @return This builder for chaining.
     */
    public Builder setAnnotatedImage(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      annotatedImage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JPEG 标注图
     * </pre>
     *
     * <code>bytes annotated_image = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnnotatedImage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      annotatedImage_ = getDefaultInstance().getAnnotatedImage();
      onChanged();
      return this;
    }

    private int processingTimeMs_ ;
    /**
     * <code>int32 processing_time_ms = 4;</code>
     * @return The processingTimeMs.
     */
    @java.lang.Override
    public int getProcessingTimeMs() {
      return processingTimeMs_;
    }
    /**
     * <code>int32 processing_time_ms = 4;</code>
     * @param value The processingTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setProcessingTimeMs(int value) {

      processingTimeMs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 processing_time_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessingTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      processingTimeMs_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yolo.AggregateDetectResponse)
  }

  // @@protoc_insertion_point(class_scope:yolo.AggregateDetectResponse)
  private static final com.yolo.proto.AggregateDetectResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yolo.proto.AggregateDetectResponse();
  }

  public static com.yolo.proto.AggregateDetectResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AggregateDetectResponse>
      PARSER = new com.google.protobuf.AbstractParser<AggregateDetectResponse>() {
    @java.lang.Override
    public AggregateDetectResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AggregateDetectResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AggregateDetectResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yolo.proto.AggregateDetectResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

