// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

public interface BoundingBoxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yolo.BoundingBox)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x1 = 1;</code>
   * @return The x1.
   */
  float getX1();

  /**
   * <code>float y1 = 2;</code>
   * @return The y1.
   */
  float getY1();

  /**
   * <code>float x2 = 3;</code>
   * @return The x2.
   */
  float getX2();

  /**
   * <code>float y2 = 4;</code>
   * @return The y2.
   */
  float getY2();

  /**
   * <code>float x3 = 5;</code>
   * @return The x3.
   */
  float getX3();

  /**
   * <code>float y3 = 6;</code>
   * @return The y3.
   */
  float getY3();

  /**
   * <code>float x4 = 7;</code>
   * @return The x4.
   */
  float getX4();

  /**
   * <code>float y4 = 8;</code>
   * @return The y4.
   */
  float getY4();
}
