// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

/**
 * <pre>
 * ============================================================
 * 旋转边界框
 * ============================================================
 * </pre>
 *
 * Protobuf type {@code yolo.BoundingBox}
 */
public final class BoundingBox extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yolo.BoundingBox)
    BoundingBoxOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoundingBox.newBuilder() to construct.
  private BoundingBox(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoundingBox() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BoundingBox();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_BoundingBox_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_BoundingBox_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yolo.proto.BoundingBox.class, com.yolo.proto.BoundingBox.Builder.class);
  }

  public static final int X1_FIELD_NUMBER = 1;
  private float x1_ = 0F;
  /**
   * <code>float x1 = 1;</code>
   * @return The x1.
   */
  @java.lang.Override
  public float getX1() {
    return x1_;
  }

  public static final int Y1_FIELD_NUMBER = 2;
  private float y1_ = 0F;
  /**
   * <code>float y1 = 2;</code>
   * @return The y1.
   */
  @java.lang.Override
  public float getY1() {
    return y1_;
  }

  public static final int X2_FIELD_NUMBER = 3;
  private float x2_ = 0F;
  /**
   * <code>float x2 = 3;</code>
   * @return The x2.
   */
  @java.lang.Override
  public float getX2() {
    return x2_;
  }

  public static final int Y2_FIELD_NUMBER = 4;
  private float y2_ = 0F;
  /**
   * <code>float y2 = 4;</code>
   * @return The y2.
   */
  @java.lang.Override
  public float getY2() {
    return y2_;
  }

  public static final int X3_FIELD_NUMBER = 5;
  private float x3_ = 0F;
  /**
   * <code>float x3 = 5;</code>
   * @return The x3.
   */
  @java.lang.Override
  public float getX3() {
    return x3_;
  }

  public static final int Y3_FIELD_NUMBER = 6;
  private float y3_ = 0F;
  /**
   * <code>float y3 = 6;</code>
   * @return The y3.
   */
  @java.lang.Override
  public float getY3() {
    return y3_;
  }

  public static final int X4_FIELD_NUMBER = 7;
  private float x4_ = 0F;
  /**
   * <code>float x4 = 7;</code>
   * @return The x4.
   */
  @java.lang.Override
  public float getX4() {
    return x4_;
  }

  public static final int Y4_FIELD_NUMBER = 8;
  private float y4_ = 0F;
  /**
   * <code>float y4 = 8;</code>
   * @return The y4.
   */
  @java.lang.Override
  public float getY4() {
    return y4_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(x1_) != 0) {
      output.writeFloat(1, x1_);
    }
    if (java.lang.Float.floatToRawIntBits(y1_) != 0) {
      output.writeFloat(2, y1_);
    }
    if (java.lang.Float.floatToRawIntBits(x2_) != 0) {
      output.writeFloat(3, x2_);
    }
    if (java.lang.Float.floatToRawIntBits(y2_) != 0) {
      output.writeFloat(4, y2_);
    }
    if (java.lang.Float.floatToRawIntBits(x3_) != 0) {
      output.writeFloat(5, x3_);
    }
    if (java.lang.Float.floatToRawIntBits(y3_) != 0) {
      output.writeFloat(6, y3_);
    }
    if (java.lang.Float.floatToRawIntBits(x4_) != 0) {
      output.writeFloat(7, x4_);
    }
    if (java.lang.Float.floatToRawIntBits(y4_) != 0) {
      output.writeFloat(8, y4_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(x1_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, x1_);
    }
    if (java.lang.Float.floatToRawIntBits(y1_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, y1_);
    }
    if (java.lang.Float.floatToRawIntBits(x2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, x2_);
    }
    if (java.lang.Float.floatToRawIntBits(y2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, y2_);
    }
    if (java.lang.Float.floatToRawIntBits(x3_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, x3_);
    }
    if (java.lang.Float.floatToRawIntBits(y3_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, y3_);
    }
    if (java.lang.Float.floatToRawIntBits(x4_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, x4_);
    }
    if (java.lang.Float.floatToRawIntBits(y4_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, y4_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yolo.proto.BoundingBox)) {
      return super.equals(obj);
    }
    com.yolo.proto.BoundingBox other = (com.yolo.proto.BoundingBox) obj;

    if (java.lang.Float.floatToIntBits(getX1())
        != java.lang.Float.floatToIntBits(
            other.getX1())) return false;
    if (java.lang.Float.floatToIntBits(getY1())
        != java.lang.Float.floatToIntBits(
            other.getY1())) return false;
    if (java.lang.Float.floatToIntBits(getX2())
        != java.lang.Float.floatToIntBits(
            other.getX2())) return false;
    if (java.lang.Float.floatToIntBits(getY2())
        != java.lang.Float.floatToIntBits(
            other.getY2())) return false;
    if (java.lang.Float.floatToIntBits(getX3())
        != java.lang.Float.floatToIntBits(
            other.getX3())) return false;
    if (java.lang.Float.floatToIntBits(getY3())
        != java.lang.Float.floatToIntBits(
            other.getY3())) return false;
    if (java.lang.Float.floatToIntBits(getX4())
        != java.lang.Float.floatToIntBits(
            other.getX4())) return false;
    if (java.lang.Float.floatToIntBits(getY4())
        != java.lang.Float.floatToIntBits(
            other.getY4())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X1_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX1());
    hash = (37 * hash) + Y1_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY1());
    hash = (37 * hash) + X2_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX2());
    hash = (37 * hash) + Y2_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY2());
    hash = (37 * hash) + X3_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX3());
    hash = (37 * hash) + Y3_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY3());
    hash = (37 * hash) + X4_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX4());
    hash = (37 * hash) + Y4_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY4());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yolo.proto.BoundingBox parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.BoundingBox parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.BoundingBox parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yolo.proto.BoundingBox parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yolo.proto.BoundingBox parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.BoundingBox parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yolo.proto.BoundingBox prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ============================================================
   * 旋转边界框
   * ============================================================
   * </pre>
   *
   * Protobuf type {@code yolo.BoundingBox}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yolo.BoundingBox)
      com.yolo.proto.BoundingBoxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_BoundingBox_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_BoundingBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yolo.proto.BoundingBox.class, com.yolo.proto.BoundingBox.Builder.class);
    }

    // Construct using com.yolo.proto.BoundingBox.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      x1_ = 0F;
      y1_ = 0F;
      x2_ = 0F;
      y2_ = 0F;
      x3_ = 0F;
      y3_ = 0F;
      x4_ = 0F;
      y4_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_BoundingBox_descriptor;
    }

    @java.lang.Override
    public com.yolo.proto.BoundingBox getDefaultInstanceForType() {
      return com.yolo.proto.BoundingBox.getDefaultInstance();
    }

    @java.lang.Override
    public com.yolo.proto.BoundingBox build() {
      com.yolo.proto.BoundingBox result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yolo.proto.BoundingBox buildPartial() {
      com.yolo.proto.BoundingBox result = new com.yolo.proto.BoundingBox(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yolo.proto.BoundingBox result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.x1_ = x1_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.y1_ = y1_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.x2_ = x2_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.y2_ = y2_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.x3_ = x3_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.y3_ = y3_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.x4_ = x4_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.y4_ = y4_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yolo.proto.BoundingBox) {
        return mergeFrom((com.yolo.proto.BoundingBox)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yolo.proto.BoundingBox other) {
      if (other == com.yolo.proto.BoundingBox.getDefaultInstance()) return this;
      if (other.getX1() != 0F) {
        setX1(other.getX1());
      }
      if (other.getY1() != 0F) {
        setY1(other.getY1());
      }
      if (other.getX2() != 0F) {
        setX2(other.getX2());
      }
      if (other.getY2() != 0F) {
        setY2(other.getY2());
      }
      if (other.getX3() != 0F) {
        setX3(other.getX3());
      }
      if (other.getY3() != 0F) {
        setY3(other.getY3());
      }
      if (other.getX4() != 0F) {
        setX4(other.getX4());
      }
      if (other.getY4() != 0F) {
        setY4(other.getY4());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              x1_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              y1_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              x2_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              y2_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 45: {
              x3_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            case 53: {
              y3_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 61: {
              x4_ = input.readFloat();
              bitField0_ |= 0x00000040;
              break;
            } // case 61
            case 69: {
              y4_ = input.readFloat();
              bitField0_ |= 0x00000080;
              break;
            } // case 69
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float x1_ ;
    /**
     * <code>float x1 = 1;</code>
     * @return The x1.
     */
    @java.lang.Override
    public float getX1() {
      return x1_;
    }
    /**
     * <code>float x1 = 1;</code>
     * @param value The x1 to set.
     * @return This builder for chaining.
     */
    public Builder setX1(float value) {

      x1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float x1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x1_ = 0F;
      onChanged();
      return this;
    }

    private float y1_ ;
    /**
     * <code>float y1 = 2;</code>
     * @return The y1.
     */
    @java.lang.Override
    public float getY1() {
      return y1_;
    }
    /**
     * <code>float y1 = 2;</code>
     * @param value The y1 to set.
     * @return This builder for chaining.
     */
    public Builder setY1(float value) {

      y1_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float y1 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearY1() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y1_ = 0F;
      onChanged();
      return this;
    }

    private float x2_ ;
    /**
     * <code>float x2 = 3;</code>
     * @return The x2.
     */
    @java.lang.Override
    public float getX2() {
      return x2_;
    }
    /**
     * <code>float x2 = 3;</code>
     * @param value The x2 to set.
     * @return This builder for chaining.
     */
    public Builder setX2(float value) {

      x2_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float x2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearX2() {
      bitField0_ = (bitField0_ & ~0x00000004);
      x2_ = 0F;
      onChanged();
      return this;
    }

    private float y2_ ;
    /**
     * <code>float y2 = 4;</code>
     * @return The y2.
     */
    @java.lang.Override
    public float getY2() {
      return y2_;
    }
    /**
     * <code>float y2 = 4;</code>
     * @param value The y2 to set.
     * @return This builder for chaining.
     */
    public Builder setY2(float value) {

      y2_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float y2 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearY2() {
      bitField0_ = (bitField0_ & ~0x00000008);
      y2_ = 0F;
      onChanged();
      return this;
    }

    private float x3_ ;
    /**
     * <code>float x3 = 5;</code>
     * @return The x3.
     */
    @java.lang.Override
    public float getX3() {
      return x3_;
    }
    /**
     * <code>float x3 = 5;</code>
     * @param value The x3 to set.
     * @return This builder for chaining.
     */
    public Builder setX3(float value) {

      x3_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float x3 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearX3() {
      bitField0_ = (bitField0_ & ~0x00000010);
      x3_ = 0F;
      onChanged();
      return this;
    }

    private float y3_ ;
    /**
     * <code>float y3 = 6;</code>
     * @return The y3.
     */
    @java.lang.Override
    public float getY3() {
      return y3_;
    }
    /**
     * <code>float y3 = 6;</code>
     * @param value The y3 to set.
     * @return This builder for chaining.
     */
    public Builder setY3(float value) {

      y3_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float y3 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearY3() {
      bitField0_ = (bitField0_ & ~0x00000020);
      y3_ = 0F;
      onChanged();
      return this;
    }

    private float x4_ ;
    /**
     * <code>float x4 = 7;</code>
     * @return The x4.
     */
    @java.lang.Override
    public float getX4() {
      return x4_;
    }
    /**
     * <code>float x4 = 7;</code>
     * @param value The x4 to set.
     * @return This builder for chaining.
     */
    public Builder setX4(float value) {

      x4_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>float x4 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearX4() {
      bitField0_ = (bitField0_ & ~0x00000040);
      x4_ = 0F;
      onChanged();
      return this;
    }

    private float y4_ ;
    /**
     * <code>float y4 = 8;</code>
     * @return The y4.
     */
    @java.lang.Override
    public float getY4() {
      return y4_;
    }
    /**
     * <code>float y4 = 8;</code>
     * @param value The y4 to set.
     * @return This builder for chaining.
     */
    public Builder setY4(float value) {

      y4_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>float y4 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearY4() {
      bitField0_ = (bitField0_ & ~0x00000080);
      y4_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yolo.BoundingBox)
  }

  // @@protoc_insertion_point(class_scope:yolo.BoundingBox)
  private static final com.yolo.proto.BoundingBox DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yolo.proto.BoundingBox();
  }

  public static com.yolo.proto.BoundingBox getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoundingBox>
      PARSER = new com.google.protobuf.AbstractParser<BoundingBox>() {
    @java.lang.Override
    public BoundingBox parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BoundingBox> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoundingBox> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yolo.proto.BoundingBox getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

