// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

/**
 * <pre>
 * ============================================================
 * 单个检测目标
 * ============================================================
 * </pre>
 *
 * Protobuf type {@code yolo.Detection}
 */
public final class Detection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yolo.Detection)
    DetectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Detection.newBuilder() to construct.
  private Detection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Detection() {
    className_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Detection();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_Detection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_Detection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yolo.proto.Detection.class, com.yolo.proto.Detection.Builder.class);
  }

  private int bitField0_;
  public static final int CLASS_ID_FIELD_NUMBER = 1;
  private int classId_ = 0;
  /**
   * <code>int32 class_id = 1;</code>
   * @return The classId.
   */
  @java.lang.Override
  public int getClassId() {
    return classId_;
  }

  public static final int CLASS_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object className_ = "";
  /**
   * <code>string class_name = 2;</code>
   * @return The className.
   */
  @java.lang.Override
  public java.lang.String getClassName() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      className_ = s;
      return s;
    }
  }
  /**
   * <code>string class_name = 2;</code>
   * @return The bytes for className.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClassNameBytes() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      className_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 3;
  private float confidence_ = 0F;
  /**
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }

  public static final int BBOX_FIELD_NUMBER = 4;
  private com.yolo.proto.BoundingBox bbox_;
  /**
   * <code>.yolo.BoundingBox bbox = 4;</code>
   * @return Whether the bbox field is set.
   */
  @java.lang.Override
  public boolean hasBbox() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.yolo.BoundingBox bbox = 4;</code>
   * @return The bbox.
   */
  @java.lang.Override
  public com.yolo.proto.BoundingBox getBbox() {
    return bbox_ == null ? com.yolo.proto.BoundingBox.getDefaultInstance() : bbox_;
  }
  /**
   * <code>.yolo.BoundingBox bbox = 4;</code>
   */
  @java.lang.Override
  public com.yolo.proto.BoundingBoxOrBuilder getBboxOrBuilder() {
    return bbox_ == null ? com.yolo.proto.BoundingBox.getDefaultInstance() : bbox_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (classId_ != 0) {
      output.writeInt32(1, classId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, className_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      output.writeFloat(3, confidence_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getBbox());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (classId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, classId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, className_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, confidence_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBbox());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yolo.proto.Detection)) {
      return super.equals(obj);
    }
    com.yolo.proto.Detection other = (com.yolo.proto.Detection) obj;

    if (getClassId()
        != other.getClassId()) return false;
    if (!getClassName()
        .equals(other.getClassName())) return false;
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (hasBbox() != other.hasBbox()) return false;
    if (hasBbox()) {
      if (!getBbox()
          .equals(other.getBbox())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLASS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClassId();
    hash = (37 * hash) + CLASS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getClassName().hashCode();
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    if (hasBbox()) {
      hash = (37 * hash) + BBOX_FIELD_NUMBER;
      hash = (53 * hash) + getBbox().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yolo.proto.Detection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.Detection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.Detection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.Detection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.Detection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.Detection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.Detection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.Detection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yolo.proto.Detection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yolo.proto.Detection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yolo.proto.Detection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.Detection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yolo.proto.Detection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ============================================================
   * 单个检测目标
   * ============================================================
   * </pre>
   *
   * Protobuf type {@code yolo.Detection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yolo.Detection)
      com.yolo.proto.DetectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_Detection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_Detection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yolo.proto.Detection.class, com.yolo.proto.Detection.Builder.class);
    }

    // Construct using com.yolo.proto.Detection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBboxFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      classId_ = 0;
      className_ = "";
      confidence_ = 0F;
      bbox_ = null;
      if (bboxBuilder_ != null) {
        bboxBuilder_.dispose();
        bboxBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_Detection_descriptor;
    }

    @java.lang.Override
    public com.yolo.proto.Detection getDefaultInstanceForType() {
      return com.yolo.proto.Detection.getDefaultInstance();
    }

    @java.lang.Override
    public com.yolo.proto.Detection build() {
      com.yolo.proto.Detection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yolo.proto.Detection buildPartial() {
      com.yolo.proto.Detection result = new com.yolo.proto.Detection(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yolo.proto.Detection result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.classId_ = classId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.className_ = className_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.confidence_ = confidence_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bbox_ = bboxBuilder_ == null
            ? bbox_
            : bboxBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yolo.proto.Detection) {
        return mergeFrom((com.yolo.proto.Detection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yolo.proto.Detection other) {
      if (other == com.yolo.proto.Detection.getDefaultInstance()) return this;
      if (other.getClassId() != 0) {
        setClassId(other.getClassId());
      }
      if (!other.getClassName().isEmpty()) {
        className_ = other.className_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getConfidence() != 0F) {
        setConfidence(other.getConfidence());
      }
      if (other.hasBbox()) {
        mergeBbox(other.getBbox());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              classId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              className_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 29: {
              confidence_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 34: {
              input.readMessage(
                  getBboxFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int classId_ ;
    /**
     * <code>int32 class_id = 1;</code>
     * @return The classId.
     */
    @java.lang.Override
    public int getClassId() {
      return classId_;
    }
    /**
     * <code>int32 class_id = 1;</code>
     * @param value The classId to set.
     * @return This builder for chaining.
     */
    public Builder setClassId(int value) {

      classId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 class_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      classId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object className_ = "";
    /**
     * <code>string class_name = 2;</code>
     * @return The className.
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string class_name = 2;</code>
     * @return The bytes for className.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string class_name = 2;</code>
     * @param value The className to set.
     * @return This builder for chaining.
     */
    public Builder setClassName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      className_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string class_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassName() {
      className_ = getDefaultInstance().getClassName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string class_name = 2;</code>
     * @param value The bytes for className to set.
     * @return This builder for chaining.
     */
    public Builder setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      className_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private float confidence_ ;
    /**
     * <code>float confidence = 3;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <code>float confidence = 3;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {

      confidence_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float confidence = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      bitField0_ = (bitField0_ & ~0x00000004);
      confidence_ = 0F;
      onChanged();
      return this;
    }

    private com.yolo.proto.BoundingBox bbox_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.yolo.proto.BoundingBox, com.yolo.proto.BoundingBox.Builder, com.yolo.proto.BoundingBoxOrBuilder> bboxBuilder_;
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     * @return Whether the bbox field is set.
     */
    public boolean hasBbox() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     * @return The bbox.
     */
    public com.yolo.proto.BoundingBox getBbox() {
      if (bboxBuilder_ == null) {
        return bbox_ == null ? com.yolo.proto.BoundingBox.getDefaultInstance() : bbox_;
      } else {
        return bboxBuilder_.getMessage();
      }
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    public Builder setBbox(com.yolo.proto.BoundingBox value) {
      if (bboxBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bbox_ = value;
      } else {
        bboxBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    public Builder setBbox(
        com.yolo.proto.BoundingBox.Builder builderForValue) {
      if (bboxBuilder_ == null) {
        bbox_ = builderForValue.build();
      } else {
        bboxBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    public Builder mergeBbox(com.yolo.proto.BoundingBox value) {
      if (bboxBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          bbox_ != null &&
          bbox_ != com.yolo.proto.BoundingBox.getDefaultInstance()) {
          getBboxBuilder().mergeFrom(value);
        } else {
          bbox_ = value;
        }
      } else {
        bboxBuilder_.mergeFrom(value);
      }
      if (bbox_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    public Builder clearBbox() {
      bitField0_ = (bitField0_ & ~0x00000008);
      bbox_ = null;
      if (bboxBuilder_ != null) {
        bboxBuilder_.dispose();
        bboxBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    public com.yolo.proto.BoundingBox.Builder getBboxBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getBboxFieldBuilder().getBuilder();
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    public com.yolo.proto.BoundingBoxOrBuilder getBboxOrBuilder() {
      if (bboxBuilder_ != null) {
        return bboxBuilder_.getMessageOrBuilder();
      } else {
        return bbox_ == null ?
            com.yolo.proto.BoundingBox.getDefaultInstance() : bbox_;
      }
    }
    /**
     * <code>.yolo.BoundingBox bbox = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.yolo.proto.BoundingBox, com.yolo.proto.BoundingBox.Builder, com.yolo.proto.BoundingBoxOrBuilder> 
        getBboxFieldBuilder() {
      if (bboxBuilder_ == null) {
        bboxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.yolo.proto.BoundingBox, com.yolo.proto.BoundingBox.Builder, com.yolo.proto.BoundingBoxOrBuilder>(
                getBbox(),
                getParentForChildren(),
                isClean());
        bbox_ = null;
      }
      return bboxBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yolo.Detection)
  }

  // @@protoc_insertion_point(class_scope:yolo.Detection)
  private static final com.yolo.proto.Detection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yolo.proto.Detection();
  }

  public static com.yolo.proto.Detection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Detection>
      PARSER = new com.google.protobuf.AbstractParser<Detection>() {
    @java.lang.Override
    public Detection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Detection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Detection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yolo.proto.Detection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

