// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

public interface DetectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yolo.Detection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 class_id = 1;</code>
   * @return The classId.
   */
  int getClassId();

  /**
   * <code>string class_name = 2;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <code>string class_name = 2;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <code>.yolo.BoundingBox bbox = 4;</code>
   * @return Whether the bbox field is set.
   */
  boolean hasBbox();
  /**
   * <code>.yolo.BoundingBox bbox = 4;</code>
   * @return The bbox.
   */
  com.yolo.proto.BoundingBox getBbox();
  /**
   * <code>.yolo.BoundingBox bbox = 4;</code>
   */
  com.yolo.proto.BoundingBoxOrBuilder getBboxOrBuilder();
}
