// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

/**
 * <pre>
 * ============================================================
 * 单张图片检测 — 请求（后端推理使用）
 * ============================================================
 * </pre>
 *
 * Protobuf type {@code yolo.ModelDetectRequest}
 */
public final class ModelDetectRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yolo.ModelDetectRequest)
    ModelDetectRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelDetectRequest.newBuilder() to construct.
  private ModelDetectRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelDetectRequest() {
    imageData_ = com.google.protobuf.ByteString.EMPTY;
    dataSource_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelDetectRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_ModelDetectRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yolo.proto.YoloDetect.internal_static_yolo_ModelDetectRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yolo.proto.ModelDetectRequest.class, com.yolo.proto.ModelDetectRequest.Builder.class);
  }

  public static final int IMAGE_DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * JPEG/PNG 编码的图片二进制数据
   * </pre>
   *
   * <code>bytes image_data = 1;</code>
   * @return The imageData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImageData() {
    return imageData_;
  }

  public static final int CONF_THRESHOLD_FIELD_NUMBER = 2;
  private float confThreshold_ = 0F;
  /**
   * <pre>
   * 置信度阈值（默认 0.5）
   * </pre>
   *
   * <code>float conf_threshold = 2;</code>
   * @return The confThreshold.
   */
  @java.lang.Override
  public float getConfThreshold() {
    return confThreshold_;
  }

  public static final int DATA_SOURCE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataSource_ = "";
  /**
   * <pre>
   * 数据来源：satellite / drone（预留）
   * </pre>
   *
   * <code>string data_source = 3;</code>
   * @return The dataSource.
   */
  @java.lang.Override
  public java.lang.String getDataSource() {
    java.lang.Object ref = dataSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataSource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 数据来源：satellite / drone（预留）
   * </pre>
   *
   * <code>string data_source = 3;</code>
   * @return The bytes for dataSource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataSourceBytes() {
    java.lang.Object ref = dataSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!imageData_.isEmpty()) {
      output.writeBytes(1, imageData_);
    }
    if (java.lang.Float.floatToRawIntBits(confThreshold_) != 0) {
      output.writeFloat(2, confThreshold_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataSource_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataSource_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!imageData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, imageData_);
    }
    if (java.lang.Float.floatToRawIntBits(confThreshold_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, confThreshold_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataSource_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataSource_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yolo.proto.ModelDetectRequest)) {
      return super.equals(obj);
    }
    com.yolo.proto.ModelDetectRequest other = (com.yolo.proto.ModelDetectRequest) obj;

    if (!getImageData()
        .equals(other.getImageData())) return false;
    if (java.lang.Float.floatToIntBits(getConfThreshold())
        != java.lang.Float.floatToIntBits(
            other.getConfThreshold())) return false;
    if (!getDataSource()
        .equals(other.getDataSource())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImageData().hashCode();
    hash = (37 * hash) + CONF_THRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfThreshold());
    hash = (37 * hash) + DATA_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getDataSource().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yolo.proto.ModelDetectRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yolo.proto.ModelDetectRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yolo.proto.ModelDetectRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.yolo.proto.ModelDetectRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yolo.proto.ModelDetectRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ============================================================
   * 单张图片检测 — 请求（后端推理使用）
   * ============================================================
   * </pre>
   *
   * Protobuf type {@code yolo.ModelDetectRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yolo.ModelDetectRequest)
      com.yolo.proto.ModelDetectRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_ModelDetectRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_ModelDetectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yolo.proto.ModelDetectRequest.class, com.yolo.proto.ModelDetectRequest.Builder.class);
    }

    // Construct using com.yolo.proto.ModelDetectRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      imageData_ = com.google.protobuf.ByteString.EMPTY;
      confThreshold_ = 0F;
      dataSource_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yolo.proto.YoloDetect.internal_static_yolo_ModelDetectRequest_descriptor;
    }

    @java.lang.Override
    public com.yolo.proto.ModelDetectRequest getDefaultInstanceForType() {
      return com.yolo.proto.ModelDetectRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.yolo.proto.ModelDetectRequest build() {
      com.yolo.proto.ModelDetectRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yolo.proto.ModelDetectRequest buildPartial() {
      com.yolo.proto.ModelDetectRequest result = new com.yolo.proto.ModelDetectRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yolo.proto.ModelDetectRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.imageData_ = imageData_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.confThreshold_ = confThreshold_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.dataSource_ = dataSource_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yolo.proto.ModelDetectRequest) {
        return mergeFrom((com.yolo.proto.ModelDetectRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yolo.proto.ModelDetectRequest other) {
      if (other == com.yolo.proto.ModelDetectRequest.getDefaultInstance()) return this;
      if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
        setImageData(other.getImageData());
      }
      if (other.getConfThreshold() != 0F) {
        setConfThreshold(other.getConfThreshold());
      }
      if (!other.getDataSource().isEmpty()) {
        dataSource_ = other.dataSource_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              imageData_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              confThreshold_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 26: {
              dataSource_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * JPEG/PNG 编码的图片二进制数据
     * </pre>
     *
     * <code>bytes image_data = 1;</code>
     * @return The imageData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    /**
     * <pre>
     * JPEG/PNG 编码的图片二进制数据
     * </pre>
     *
     * <code>bytes image_data = 1;</code>
     * @param value The imageData to set.
     * @return This builder for chaining.
     */
    public Builder setImageData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      imageData_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JPEG/PNG 编码的图片二进制数据
     * </pre>
     *
     * <code>bytes image_data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      imageData_ = getDefaultInstance().getImageData();
      onChanged();
      return this;
    }

    private float confThreshold_ ;
    /**
     * <pre>
     * 置信度阈值（默认 0.5）
     * </pre>
     *
     * <code>float conf_threshold = 2;</code>
     * @return The confThreshold.
     */
    @java.lang.Override
    public float getConfThreshold() {
      return confThreshold_;
    }
    /**
     * <pre>
     * 置信度阈值（默认 0.5）
     * </pre>
     *
     * <code>float conf_threshold = 2;</code>
     * @param value The confThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setConfThreshold(float value) {

      confThreshold_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 置信度阈值（默认 0.5）
     * </pre>
     *
     * <code>float conf_threshold = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfThreshold() {
      bitField0_ = (bitField0_ & ~0x00000002);
      confThreshold_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object dataSource_ = "";
    /**
     * <pre>
     * 数据来源：satellite / drone（预留）
     * </pre>
     *
     * <code>string data_source = 3;</code>
     * @return The dataSource.
     */
    public java.lang.String getDataSource() {
      java.lang.Object ref = dataSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 数据来源：satellite / drone（预留）
     * </pre>
     *
     * <code>string data_source = 3;</code>
     * @return The bytes for dataSource.
     */
    public com.google.protobuf.ByteString
        getDataSourceBytes() {
      java.lang.Object ref = dataSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 数据来源：satellite / drone（预留）
     * </pre>
     *
     * <code>string data_source = 3;</code>
     * @param value The dataSource to set.
     * @return This builder for chaining.
     */
    public Builder setDataSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataSource_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据来源：satellite / drone（预留）
     * </pre>
     *
     * <code>string data_source = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataSource() {
      dataSource_ = getDefaultInstance().getDataSource();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据来源：satellite / drone（预留）
     * </pre>
     *
     * <code>string data_source = 3;</code>
     * @param value The bytes for dataSource to set.
     * @return This builder for chaining.
     */
    public Builder setDataSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataSource_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yolo.ModelDetectRequest)
  }

  // @@protoc_insertion_point(class_scope:yolo.ModelDetectRequest)
  private static final com.yolo.proto.ModelDetectRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yolo.proto.ModelDetectRequest();
  }

  public static com.yolo.proto.ModelDetectRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelDetectRequest>
      PARSER = new com.google.protobuf.AbstractParser<ModelDetectRequest>() {
    @java.lang.Override
    public ModelDetectRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ModelDetectRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelDetectRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yolo.proto.ModelDetectRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

