// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

public interface ModelDetectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yolo.ModelDetectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * JPEG/PNG 编码的图片二进制数据
   * </pre>
   *
   * <code>bytes image_data = 1;</code>
   * @return The imageData.
   */
  com.google.protobuf.ByteString getImageData();

  /**
   * <pre>
   * 置信度阈值（默认 0.5）
   * </pre>
   *
   * <code>float conf_threshold = 2;</code>
   * @return The confThreshold.
   */
  float getConfThreshold();

  /**
   * <pre>
   * 数据来源：satellite / drone（预留）
   * </pre>
   *
   * <code>string data_source = 3;</code>
   * @return The dataSource.
   */
  java.lang.String getDataSource();
  /**
   * <pre>
   * 数据来源：satellite / drone（预留）
   * </pre>
   *
   * <code>string data_source = 3;</code>
   * @return The bytes for dataSource.
   */
  com.google.protobuf.ByteString
      getDataSourceBytes();
}
