// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yolo_detect.proto

// Protobuf Java Version: 3.25.5
package com.yolo.proto;

public final class YoloDetect {
  private YoloDetect() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yolo_ModelDetectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yolo_ModelDetectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yolo_AggregateDetectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yolo_AggregateDetectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yolo_BoundingBox_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yolo_BoundingBox_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yolo_Detection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yolo_Detection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yolo_ModelDetectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yolo_ModelDetectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yolo_AggregateDetectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yolo_AggregateDetectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021yolo_detect.proto\022\004yolo\"U\n\022ModelDetect" +
      "Request\022\022\n\nimage_data\030\001 \001(\014\022\026\n\016conf_thre" +
      "shold\030\002 \001(\002\022\023\n\013data_source\030\003 \001(\t\"Y\n\026Aggr" +
      "egateDetectRequest\022\022\n\nimage_data\030\001 \001(\014\022\026" +
      "\n\016conf_threshold\030\002 \001(\002\022\023\n\013data_source\030\003 " +
      "\001(\t\"m\n\013BoundingBox\022\n\n\002x1\030\001 \001(\002\022\n\n\002y1\030\002 \001" +
      "(\002\022\n\n\002x2\030\003 \001(\002\022\n\n\002y2\030\004 \001(\002\022\n\n\002x3\030\005 \001(\002\022\n" +
      "\n\002y3\030\006 \001(\002\022\n\n\002x4\030\007 \001(\002\022\n\n\002y4\030\010 \001(\002\"f\n\tDe" +
      "tection\022\020\n\010class_id\030\001 \001(\005\022\022\n\nclass_name\030" +
      "\002 \001(\t\022\022\n\nconfidence\030\003 \001(\002\022\037\n\004bbox\030\004 \001(\0132" +
      "\021.yolo.BoundingBox\"k\n\023ModelDetectRespons" +
      "e\022#\n\ndetections\030\001 \003(\0132\017.yolo.Detection\022\023" +
      "\n\013total_count\030\002 \001(\005\022\032\n\022processing_time_m" +
      "s\030\003 \001(\005\"\210\001\n\027AggregateDetectResponse\022#\n\nd" +
      "etections\030\001 \003(\0132\017.yolo.Detection\022\023\n\013tota" +
      "l_count\030\002 \001(\005\022\027\n\017annotated_image\030\003 \001(\014\022\032" +
      "\n\022processing_time_ms\030\004 \001(\005B\022\n\016com.yolo.p" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yolo_ModelDetectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yolo_ModelDetectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yolo_ModelDetectRequest_descriptor,
        new java.lang.String[] { "ImageData", "ConfThreshold", "DataSource", });
    internal_static_yolo_AggregateDetectRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yolo_AggregateDetectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yolo_AggregateDetectRequest_descriptor,
        new java.lang.String[] { "ImageData", "ConfThreshold", "DataSource", });
    internal_static_yolo_BoundingBox_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_yolo_BoundingBox_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yolo_BoundingBox_descriptor,
        new java.lang.String[] { "X1", "Y1", "X2", "Y2", "X3", "Y3", "X4", "Y4", });
    internal_static_yolo_Detection_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_yolo_Detection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yolo_Detection_descriptor,
        new java.lang.String[] { "ClassId", "ClassName", "Confidence", "Bbox", });
    internal_static_yolo_ModelDetectResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_yolo_ModelDetectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yolo_ModelDetectResponse_descriptor,
        new java.lang.String[] { "Detections", "TotalCount", "ProcessingTimeMs", });
    internal_static_yolo_AggregateDetectResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_yolo_AggregateDetectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yolo_AggregateDetectResponse_descriptor,
        new java.lang.String[] { "Detections", "TotalCount", "AnnotatedImage", "ProcessingTimeMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
